### ISSUE TITLE
extend a list sample with List attributes

### ISSUE THREAD

**Issue by bdoubrov** [latex3/tagpdf#45]
PDF 1.7 and PDF 2.0 define the following List-owned attribute:

**ListNumbering** - The numbering system used to generate the content of the Lbl (Label) elements in an autonumbered list, or the symbol used to identify each item in an unnumbered list.

See PDF 1.7, Table 347 and its update in PDF 2.0, Table 3.8.2 (it just adds a generic ListNumbering type `Ordered` meaning "Ordered lists with unspecified numbering").

PDF 2.0 also adds two new attributes to improve the support for continued lists:
**ContinuedList** - A flag specifying whether the list is a continuation of a previous list in the structure tree (_true_), or not (_false_).
**ContinuedFrom** - The ID of the list for which this list is a continuation.

**Comment by u-fischer** [comment]
the new list code uses attributes (ContinuedList and ContinuedFrom will be used once resume-List will be implemented). So I'm closing this here. New issues should be added to https://github.com/latex3/tagging-project
