### ISSUE TITLE
setting ID entry in structure elements

### ISSUE THREAD

**Issue by lvjr** [latex3/tagpdf#62]
In the documentation of `tagpdf`, I can not find a way to set `ID` key inside `\tagstructbegin` command. `ID` key is needed by `/Headers` attribute with owner `/Table`.

**Comment by u-fischer** [comment]
no there is no IDtree currently as we didn't really started on tabulars yet, and for other structures there isn't much use for it. But it wouldn't be very difficult to add. I will look into it.

**Comment by lvjr** [comment]
Basically I know a little more `HTML/CSS` than `PDF`. Since `Tagged PDF` is similar to `HTML/CSS` in many aspects and there is a specification for deriving `HTML` from `Tagged PDF`, I think it is a good idea to understand `Tagged PDF` concepts from the point of view of `HTML/CSS`.

In `HTML/CSS`, I would think `id` and `class` attributes are two most elementary and important attributes of elements, and they can be used in almost all elements. They correspond to `ID` and `C` keys in `Tagged PDF` respectively.

**Comment by u-fischer** [comment]
I have added ID's to the structures and also the IDtree and uploaded a new version to ctan. There isn't yet a good interface to use them in attributes, I need to do more experiments first.

**Comment by u-fischer** [comment]
I'm closing as the IDtree is now there. For new question  about e.g. how to retrieve them, open a new issue.
