### ISSUE TITLE
verbatim is more widely spaced if tagging (phase-III) is activated

### ISSUE THREAD

**Issue by jfbu** [latex3/tagpdf#74]
```
\DocumentMetadata{testphase={phase-III}}
\documentclass{article}
\begin{document}
\begin{verbatim}
\documentclass{article}
\usepackage{fontspec}
\begin{document}
\Huge
$\mathit{f_i^i}$\par $\mathrm{f_i^i}$
\end{document}
\end{verbatim}
\end{document}
```
output from using ``lualatex-dev``:
![Capture d’écran 2023-05-15 à 13 42 01](https://github.com/u-fischer/tagpdf/assets/2589111/6fc628a2-84e7-48ee-b6c0-ffd8e7cacbf7)

output if first line is commented out
![Capture d’écran 2023-05-15 à 13 42 33](https://github.com/u-fischer/tagpdf/assets/2589111/fd8a6785-a81b-45c0-a208-e831197a5c86)

Same issue using `pdflatex-dev`.

Log file with `lualatex-dev` attached.
[test_tagging_verbatim.log](https://github.com/u-fischer/tagpdf/files/11477343/test_tagging_verbatim.log)

**Comment by u-fischer** [comment]
That is an issue in the block-tagging code. \parskip is not zero  @FrankMittelbach is legacyverbatimsetup the right place to add this?

~~~~
\DocumentMetadata{testphase={block-tagging}} 
\documentclass{article}
\begin{document}

\begin{verbatim}
abc
abc
\end{verbatim}

\makeatletter
\AddToHook{cmd/legacyverbatimsetup/before}{\parskip\z@skip}

\begin{verbatim}
abc
abc
\end{verbatim}
\end{document}
~~~~

![image](https://github.com/u-fischer/tagpdf/assets/4047173/252904ff-b8c8-49ed-8014-b458d740d741)

**Comment by FrankMittelbach** [comment]
it would be possible to freeze \parskip to zero as suggested, but I think it is better to use a "verbatimblock" instance to set this value as this allows designs where the code blocks are deliberately spaced out or indented or ...  This is what I have pushed in latex-lab.
