### ISSUE TITLE
Text before table environment must be separated by it from an explicit `\par` or blank line

### ISSUE THREAD

**Issue by jfbu** [latex3/tagpdf#77]
```
\DocumentMetadata{testphase={phase-III}}
\documentclass{article}
\begin{document}
\begin{table}[htbp]
First table\par
\end{table}
Text.
\begin{table}[htbp]
Second table\par
\end{table}
\end{document}
```

creates:
```
Package tagpdf Warning: Rule 'P/' --> 'text-unit/user' is not allowed (struct
(tagpdf)                5, /text --> struct 6)


Package tagpdf Warning: Rule 'P/' --> 'text/user' is not allowed (struct 6,
(tagpdf)                /text-unit --> struct 7)

```

[test_tagging_tables.log](https://github.com/u-fischer/tagpdf/files/11479533/test_tagging_tables.log)

The `Text.` must be ended by explicit `\par`, or blank line.

Caveat: before opening this ticket I only searched for "table" in file tagpdf.pdf.  Sorry if that is documented somewhare.  But I spend quite some time reducing from real life example.

**Comment by jfbu** [comment]
Actually, it is not being between two table environments, but simply being before one.
```latex
\DocumentMetadata{testphase={phase-III}}
\documentclass{article}
\begin{document}
Text.
\begin{table}[htbp]
First table\par
\end{table}
% \begin{table}[htbp]
% Second table\par
% \end{table}
\end{document}
```

```
Package tagpdf Warning: Rule 'P/' --> 'text-unit/user' is not allowed (struct
(tagpdf)                3, /text --> struct 4)


Package tagpdf Warning: Rule 'P/' --> 'text/user' is not allowed (struct 4,
(tagpdf)                /text-unit --> struct 5)
```

**Comment by u-fischer** [comment]
floats need some code that I have currently only locally. With it your code works (with and without the \par).

**Comment by u-fischer** [comment]
I'm closing this as the warnings are gone, but will open a new issue in the tagging project, as there is still a faulty mc-nesting.
