### ISSUE TITLE
Ignored leftmargin by verbatim contents after first line if nested in a list item

### ISSUE THREAD

**Issue by jfbu** [latex3/tagpdf#79]
```latex
\DocumentMetadata{testphase={phase-III}}
\documentclass{article}
\begin{document}
\begin{itemize}
\item
\begin{verbatim}
    \MTactiveasterisk
    \MTprimedoesskip
\end{verbatim}
\item Test
\begin{verbatim}
    \MTactiveasterisk
    \MTprimedoesskip
\end{verbatim}
\end{itemize}
OK if out of list item:
\begin{verbatim}
    \MTactiveasterisk
    \MTprimedoesskip
\end{verbatim}
\end{document}
```
produces

![Capture d’écran 2023-05-16 à 11 08 14](https://github.com/u-fischer/tagpdf/assets/2589111/021c89b9-034f-48d0-bba5-190d61523bd8)

[test_tagging_verbatim2.log](https://github.com/u-fischer/tagpdf/files/11485983/test_tagging_verbatim2.log)

**Comment by jfbu** [comment]
Sorry my initial title was wrong as one shows with output without activated tagging:
![Capture d’écran 2023-05-16 à 11 07 11](https://github.com/u-fischer/tagpdf/assets/2589111/bb2ca44d-bb31-4746-a9d7-37660d36c560)

**Comment by jfbu** [comment]
I edited the title to better match the problem:
```latex
\DocumentMetadata{testphase={phase-III}}
\documentclass{article}
\begin{document}
\begin{itemize}
\item
\begin{verbatim}
    \MTactiveasterisk
    \MTprimedoesskip
\end{verbatim}
\item Text
\begin{verbatim}
    \MTactiveasterisk
    \MTprimedoesskip
\end{verbatim}
\item Some sub list
  \begin{itemize}
  \item Some text before verbatim
\begin{verbatim}
\MTactiveasterisk
\MTprimedoesskip
  \MTprimedoesskip
    \MTprimedoesskip
\end{verbatim}
  \end{itemize}
\end{itemize}
OK if out of list item:
\begin{verbatim}
    \MTactiveasterisk
    \MTprimedoesskip
\end{verbatim}
\end{document}
% https://github.com/u-fischer/tagpdf/issues/79
```

![Capture d’écran 2023-05-16 à 11 25 42](https://github.com/u-fischer/tagpdf/assets/2589111/ce7bf092-16f6-4e0b-85ec-d6db7addaa61)

**Comment by FrankMittelbach** [comment]
LaTeX2e used a trivlist for verbatim and inside changed \leftskip to mimic the outer indentation. We now do not used a list anymore but this means that we need to preserve any \parshape setting from an outer list (which the code failed to do). This has been corrected in latex-lab.

**Comment by jfbu** [comment]
Will vertical spacing relative to surrounding context be faithfully obeyed by the new code not using a list?

**Comment by FrankMittelbach** [comment]
> Will vertical spacing relative to surrounding context be faithfully obeyed by the new code not using a list?

define faithfully :-) yes it should that was the plan. It is implemented as a displayblock template which handles the vertical spacing to be (by default) th same as in other display blocks, eg lists or quote etc. By using its own instance, however, a class file can decide to use special spacing around the verbatim different from, say, quote or lists which gives more choices than with the 2e implementation, but by default it should come out as before.

**Comment by jfbu** [comment]
ok since I discovered latex2e/required/latex-lab and the magic incantation `l3build doc` so I have some reading to do...
