### ISSUE TITLE
list of structure names of PDF 1.7 remains blank in tagpdf.pdf

### ISSUE THREAD

**Issue by jfbu** [latex3/tagpdf#92]
Source is 
https://github.com/latex3/tagpdf/blob/9e14eda3fdad88ace16fdd553c6e6922bac74ecf/doc/tagpdf.tex#L2133-L2139

I see this in the pdf:
![Capture d’écran 2024-01-06 à 16 52 35](https://github.com/latex3/tagpdf/assets/2589111/5f0e04d4-1517-41e1-9ec2-c5d1271374af)

**Comment by u-fischer** [comment]
Oh well, one should pay attention when the editor wraps lines. Corrected in dev.
