### ISSUE TITLE
Postscript error with basic test input and dvilualatex[-dev] + dvips + ps2pdf

### ISSUE THREAD

**Issue by agrahn** [latex3/tagpdf#96]
PS generated with `dvilualatex` or `divlualatex-dev` and `dvips` leads to this error upon `ps2pdf`:

    error: /undefined in BMC
    Operand stack:   --nostringval--   Artifact
    ...

No error, on the other hand, with `latex`+`dvips`.

Test input:

````latex
\DocumentMetadata{ testphase=phase-III }
\documentclass{article}
\usepackage[T1]{fontenc}
    
\begin{document}
  test
\end{document}
````

**Comment by agrahn** [comment]
The [`pdfmark` syntax](https://opensource.adobe.com/dc-acrobat-sdk-docs/library/pdfmark/pdfmark_Basic.html#marked-content-mp-dp-bmc-bdc-emc) requires `BMC`, `EMC` and relatives with a leading slash (PS name objects):

    [ tag /BMC pdfmark

In the `dvilualatex`+`dvips` generated PS, the slash is missing and they are seen as PS operators.  But they are not defined. Hence the error.

**Comment by u-fischer** [comment]
This has been fixed.
